import type { IGridItemLayout } from '@/types'

export function useGridItemLayout(layout: IGridItemLayout) {
  return {
    [`col-span-${layout.colSpanBase}`]: !!layout.colSpanBase,
    [`sm:col-span-${layout.colSpanSm}`]: !!layout.colSpanSm,
    [`md:col-span-${layout.colSpanMd}`]: !!layout.colSpanMd,
    [`lg:col-span-${layout.colSpanLg}`]: !!layout.colSpanLg,
    [`xl:col-span-${layout.colSpanXl}`]: !!layout.colSpanXl,
    [`2xl:col-span-${layout.colSpan2xl}`]: !!layout.colSpan2xl,
    [`col-start-${layout.colStartBase}`]: !!layout.colStartBase,
    [`sm:col-start-${layout.colStartSm}`]: !!layout.colStartSm,
    [`md:col-start-${layout.colStartMd}`]: !!layout.colStartMd,
    [`lg:col-start-${layout.colStartLg}`]: !!layout.colStartLg,
    [`xl:col-start-${layout.colStartXl}`]: !!layout.colStartXl,
    [`2xl:col-start-${layout.colStart2xl}`]: !!layout.colStart2xl,
    [`col-end-${layout.colEndBase}`]: !!layout.colEndBase,
    [`sm:col-end-${layout.colEndSm}`]: !!layout.colEndSm,
    [`md:col-end-${layout.colEndMd}`]: !!layout.colEndMd,
    [`lg:col-end-${layout.colEndLg}`]: !!layout.colEndLg,
    [`xl:col-end-${layout.colEndXl}`]: !!layout.colEndXl,
    [`2xl:col-end-${layout.colEnd2xl}`]: !!layout.colEnd2xl,
    [`row-span-${layout.rowSpanBase}`]: !!layout.rowSpanBase,
    [`sm:row-span-${layout.rowSpanSm}`]: !!layout.rowSpanSm,
    [`md:row-span-${layout.rowSpanMd}`]: !!layout.rowSpanMd,
    [`lg:row-span-${layout.rowSpanLg}`]: !!layout.rowSpanLg,
    [`xl:row-span-${layout.rowSpanXl}`]: !!layout.rowSpanXl,
    [`2xl:row-span-${layout.rowSpan2xl}`]: !!layout.rowSpan2xl,
    [`row-start-${layout.rowStartBase}`]: !!layout.rowStartBase,
    [`sm:row-start-${layout.rowStartSm}`]: !!layout.rowStartSm,
    [`md:row-start-${layout.rowStartMd}`]: !!layout.rowStartMd,
    [`lg:row-start-${layout.rowStartLg}`]: !!layout.rowStartLg,
    [`xl:row-start-${layout.rowStartXl}`]: !!layout.rowStartXl,
    [`2xl:row-start-${layout.rowStart2xl}`]: !!layout.rowStart2xl,
    [`row-end-${layout.rowEndBase}`]: !!layout.rowEndBase,
    [`sm:row-end-${layout.rowEndSm}`]: !!layout.rowEndSm,
    [`md:row-end-${layout.rowEndMd}`]: !!layout.rowEndMd,
    [`lg:row-end-${layout.rowEndLg}`]: !!layout.rowEndLg,
    [`xl:row-end-${layout.rowEndXl}`]: !!layout.rowEndXl,
    [`2xl:row-end-${layout.rowEnd2xl}`]: !!layout.rowEnd2xl,
    [`justify-self-${layout.justifySelfBase}`]: !!layout.justifySelfBase,
    [`sm:justify-self-${layout.justifySelfSm}`]: !!layout.justifySelfSm,
    [`md:justify-self-${layout.justifySelfMd}`]: !!layout.justifySelfMd,
    [`lg:justify-self-${layout.justifySelfLg}`]: !!layout.justifySelfLg,
    [`xl:justify-self-${layout.justifySelfXl}`]: !!layout.justifySelfXl,
    [`2xl:justify-self-${layout.justifySelf2xl}`]: !!layout.justifySelf2xl,
    [`self-${layout.alignSelfBase}`]: !!layout.alignSelfBase,
    [`sm:self-${layout.alignSelfSm}`]: !!layout.alignSelfSm,
    [`md:self-${layout.alignSelfMd}`]: !!layout.alignSelfMd,
    [`lg:self-${layout.alignSelfLg}`]: !!layout.alignSelfLg,
    [`xl:self-${layout.alignSelfXl}`]: !!layout.alignSelfXl,
    [`2xl:self-${layout.alignSelf2xl}`]: !!layout.alignSelf2xl
  }
}
