import type { IGridLayout } from '@/types'

export function useGridLayout(layout: IGridLayout) {
  return [
    'grid',
    {
      'h-full': !!layout.fullHeight,
      [`grid-flow-${layout.autoFlow}`]: !!layout.autoFlow,
      [`grid-cols-${layout.colsBase}`]: !!layout.colsBase,
      [`sm:grid-cols-${layout.colsSm}`]: !!layout.colsSm,
      [`md:grid-cols-${layout.colsMd}`]: !!layout.colsMd,
      [`lg:grid-cols-${layout.colsLg}`]: !!layout.colsLg,
      [`xl:grid-cols-${layout.colsXl}`]: !!layout.colsXl,
      [`2xl:grid-cols-${layout.cols2xl}`]: !!layout.cols2xl,
      [`grid-rows-${layout.rowsBase}`]: !!layout.rowsBase,
      [`sm:grid-rows-${layout.rowsSm}`]: !!layout.rowsSm,
      [`md:grid-rows-${layout.rowsMd}`]: !!layout.rowsMd,
      [`lg:grid-rows-${layout.rowsLg}`]: !!layout.rowsLg,
      [`xl:grid-rows-${layout.rowsXl}`]: !!layout.rowsXl,
      [`2xl:grid-rows-${layout.rows2xl}`]: !!layout.rows2xl,
      [`gap-x-${layout.gapXAxisBase}`]: !!layout.gapXAxisBase,
      [`sm:gap-x-${layout.gapXAxisSm}`]: !!layout.gapXAxisSm,
      [`md:gap-x-${layout.gapXAxisMd}`]: !!layout.gapXAxisMd,
      [`lg:gap-x-${layout.gapXAxisLg}`]: !!layout.gapXAxisLg,
      [`xl:gap-x-${layout.gapXAxisXl}`]: !!layout.gapXAxisXl,
      [`2xl:gap-x-${layout.gapXAxis2xl}`]: !!layout.gapXAxis2xl,
      [`gap-y-${layout.gapYAxisBase}`]: !!layout.gapYAxisBase,
      [`sm:gap-y-${layout.gapYAxisSm}`]: !!layout.gapYAxisSm,
      [`md:gap-y-${layout.gapYAxisMd}`]: !!layout.gapYAxisMd,
      [`lg:gap-y-${layout.gapYAxisLg}`]: !!layout.gapYAxisLg,
      [`xl:gap-y-${layout.gapYAxisXl}`]: !!layout.gapYAxisXl,
      [`2xl:gap-y-${layout.gapYAxis2xl}`]: !!layout.gapYAxis2xl,
      [`content-${layout.alignContentBase}`]: !!layout.alignContentBase,
      [`sm:content-${layout.alignContentSm}`]: !!layout.alignContentSm,
      [`md:content-${layout.alignContentMd}`]: !!layout.alignContentMd,
      [`lg:content-${layout.alignContentLg}`]: !!layout.alignContentLg,
      [`xl:content-${layout.alignContentXl}`]: !!layout.alignContentXl,
      [`2xl:content-${layout.alignContent2xl}`]: !!layout.alignContent2xl,
      [`place-content-${layout.placeContentBase}`]: !!layout.placeContentBase,
      [`sm:place-content-${layout.placeContentSm}`]: !!layout.placeContentSm,
      [`md:place-content-${layout.placeContentMd}`]: !!layout.placeContentMd,
      [`lg:place-content-${layout.placeContentLg}`]: !!layout.placeContentLg,
      [`xl:place-content-${layout.placeContentXl}`]: !!layout.placeContentXl,
      [`2xl:place-content-${layout.placeContent2xl}`]: !!layout.placeContent2xl,
      [`place-items-${layout.placeItemsBase}`]: !!layout.placeItemsBase,
      [`sm:place-items-${layout.placeItemsSm}`]: !!layout.placeItemsSm,
      [`md:place-items-${layout.placeItemsMd}`]: !!layout.placeItemsMd,
      [`lg:place-items-${layout.placeItemsLg}`]: !!layout.placeItemsLg,
      [`xl:place-items-${layout.placeItemsXl}`]: !!layout.placeItemsXl,
      [`2xl:place-items-${layout.placeItems2xl}`]: !!layout.placeItems2xl,
      [`justify-items-${layout.justifyItemsBase}`]: !!layout.justifyItemsBase,
      [`sm:justify-items-${layout.justifyItemsSm}`]: !!layout.justifyItemsSm,
      [`md:justify-items-${layout.justifyItemsMd}`]: !!layout.justifyItemsMd,
      [`lg:justify-items-${layout.justifyItemsLg}`]: !!layout.justifyItemsLg,
      [`xl:justify-items-${layout.justifyItemsXl}`]: !!layout.justifyItemsXl,
      [`2xl:justify-items-${layout.justifyItems2xl}`]: !!layout.justifyItems2xl
    }
  ]
}
